version: "3"
services:
  develop:
    build: .
    ports:
      - "35739:35729"
    environment:
      CT_REGISTER_MODE: auto
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:5005
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      API_VERSION: v1
    command: develop
    volumes:
      - ./app:/opt/task-executor/app
    links:
      - mongo
  mongo:
    image: mongo:3.4
    container_name: task-executor-mongo-develop
    command: --smallfiles
    ports:
      - "27017"
    volumes:
      - $HOME/docker/data/task-executor:/data/db
    restart: always
